/* THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT. */
/* See the input xml tasks-cfg/test.cfg */

#ifndef __CONFIG_H
#define __CONFIG_H

#include <task.h>

#define MILISECOND ((CPU_FREQ/2)/ 1000)
#define UART_SPEED 115200
#define QUANTUM_SCHEDULER_MS 10 
#define GUEST_QUANTUM_MS 1 

static const struct tasksconf_t const VMCONF[] = {
	{
		app_name: "test-tasks",
		priority: 100,
		ram_base: 0x80004,
		size: 0x1000,
	},
	{
		app_name: "test-tasks2",
		priority: 100,
		ram_base: 0x80005,
		size: 0x1000,
	},
};

/* Virtual Machine names: test-tasks test-tasks2*/
#define NVMACHINES 2

#endif